name: EventFramework
main: me.squeeglii.plugin.eventfw.EventFramework

version: '${plugin_version}'
api-version: '${minecraft_version}'

authors: [ 'Squeeglii' ]
description: Adds tools for hosting in-world events in Minecraft.
